version: '3.4'

services:
  mapentitiesservice:
    image: ${DOCKER_REGISTRY-}mapentitiesservice
    build:
      context: .
      dockerfile: MapEntitiesService/Dockerfile
    networks:
        - default

  notificationsservice:
    image: ${DOCKER_REGISTRY-}notificationsservice
    build:
      context: .
      dockerfile: NotificationsService/Dockerfile
    networks:
        - default

  rabbitmq:
    image: rabbitmq:3-management
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
    networks:
        - default

networks:
  default:
    driver: bridge

