version: '3.4'

services:
  mapentitiesservice:
    image: ${DOCKER_REGISTRY-}mapentitiesservice
    build:
      context: .
      dockerfile: MapEntitiesService/Dockerfile
    networks:
        - microserviceDemoNetwork

  notificationsservice:
    image: ${DOCKER_REGISTRY-}notificationsservice
    build:
      context: .
      dockerfile: NotificationsService/Dockerfile
    networks:
        - microserviceDemoNetwork

  ocelotapigw:
    image: ${DOCKER_REGISTRY-}ocelotapigw
    build:
      context: .
      dockerfile: OcelotApiGw/Dockerfile
    ports:
      - "5003:80"
    networks:
        - microserviceDemoNetwork

  rabbitmq:
    image: rabbitmq:3-management
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
    networks:
        - microserviceDemoNetwork

  seq:
    image: datalust/seq:latest
    container_name: 'loggingservice'
    ports:
      - "80:80"
      - "5341:5341"
    environment:
      - ACCEPT_EULA=Y
    volumes:
      - seq-data:/data
    networks:
      - microserviceDemoNetwork

volumes:
  seq-data:

networks:
  microserviceDemoNetwork:
    driver: bridge

